### ISSUE TITLE
Integrate with bloc-did-method for sidetree-mock

### ISSUE THREAD

**Issue by fqutishat** [trustbloc/edge-sandbox#133]

**Comment by troyronda** [comment]
@fqutishat we need to show the static content feature hosted by the peers. is that a different issue?

**Comment by fqutishat** [comment]
> @fqutishat we need to show the static content feature hosted by the peers. is that a different issue?

yes I have different ticket for that https://github.com/trustbloc/edge-sandbox/pull/137
