### ISSUE TITLE
Rename resolution and ops endpoints

### ISSUE THREAD

**Issue by troyronda** [trustbloc/edge-sandbox#256]
- resolution endpoint (`<base URL>/sidetree`) is renamed to `<base URL>/identifiers`
- operations endpoint (`<base URL>/sidetree/operations`) is renamed to `<base URL>/operations`

where base URL is currently `/sidetree/api-version`

Example: `/sidetree/1.0.0/identifiers`

see https://identity.foundation/sidetree/docs/swagger/#/
note: swagger api version is technically 0.0.1, but it would be good not to break things when it gets bumped to 1.0.0.

related to: https://github.com/trustbloc/sidetree-fabric/issues/240 and https://github.com/trustbloc/sidetree-fabric/issues/241

**Comment by fqutishat** [comment]
@troyronda https://github.com/trustbloc/edge-sandbox/pull/268
