### ISSUE TITLE
strapi startup failure

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/edge-sandbox#468]
Sometimes, the strapi fails to start up when we run the demo due to various errors. Since demo already takes a while to start up and coupled with strapi failures, testing changes takes a lot of effort.

Need to figure out a solution for this.

**Comment by rolsonquadras** [comment]
With docker image update of strapi (#469), strapi started without issue 5/5 times in my machine. 

Keeping this open for couple of days to see if indeed the PR fixed the issue.

**Comment by DRK3** [comment]
@rolsonquadras Is it ok to close this issue now?

**Comment by rolsonquadras** [comment]
Yeah. Haven't heard any failures related to strapi. 

Closing the issue.
