### ISSUE TITLE
Change mDL scope name and remove trustbloc from contents 

### ISSUE THREAD

**Issue by talwinder50** [trustbloc/edge-sandbox#506]
user’s won’t understand the abbreviation “mDL” on the consent page - is there a way to make the UI show a user friendly version?

The “here is your generated credential” page has degree: null (and seems to be the degree schema rather than DL

Fix the DL data

**Comment by llorllale** [comment]
The abbreviation "mDL" on the consent page is due to the fact that the OAuth2 scope is tightly coupled to the VC generation: https://github.com/trustbloc/edge-sandbox/blob/e1ca29b3cbb25cc6497979f0181c24e7244fbfb8/pkg/restapi/issuer/operation/operations.go#L637.

**Comment by llorllale** [comment]
It would be nice if we could get rid of that consent screen altogether... why is the user consenting so many times? Should only be once (in their wallet, when the RP asks for credentials).
